// deploy/Jenkinsfile
pipeline {
    agent any
    
    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }
    
    parameters {
        choice(
            name: 'environment',
            choices: ['dev', 'staging', 'prod'],
            description: 'Select deployment environment'
        )
        
        string(
            name: 'branch',
            defaultValue: 'main',
            description: 'Branch to build'
        )
    }

    stages {
        stage('Initial Cleanup'){
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Prepare Dependencies'){
            steps {
                sh '''
                    php -v
                    composer --version
                    echo "Composer Updated"
                    composer install
                    echo "Composer Dependencies Installed"
                    cp .env.example .env
                    php artisan migrate
                    php artisan db:seed
                    php artisan key:generate
                    '''

            }
        }

        stage('Execute Tests'){
            steps {
                sh '''
                    sed -i "s/^APP_KEY=.*/APP_KEY=$(php artisan key:generate --show)/" .env
                    mkdir -p storage/framework/sessions
                    mkdir -p storage/framework/cache
                    mkdir -p storage/framework/views
                    echo "APP_KEY Updated"
                    echo "Running Tests"
                    ./vendor/bin/phpunit --log-junit tests/junit.xml
                '''
            }

            post {
                always {
                    junit 'tests/junit.xml'
                }
            }
        }

        stage ('Code Analysis'){
            steps{
                sh '''
                    mkdir -p build/logs/
                    /usr/local/bin/phploc app/ --log-csv build/logs/phploc.csv
                    '''
            }
        }

        stage('Plot Code Coverage Report') {
    steps {
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Lines of Code (LOC),Comment Lines of Code (CLOC),Non-Comment Lines of Code (NCLOC),Logical Lines of Code (LLOC)', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'A - Lines of code', 
             yaxis: 'Lines of Code'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Directories,Files,Namespaces', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'B - Structures Containers', 
             yaxis: 'Count'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Average Class Length (LLOC),Average Method Length (LLOC),Average Function Length (LLOC)', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'C - Average Length', 
             yaxis: 'Average Lines of Code'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Cyclomatic Complexity / Lines of Code,Cyclomatic Complexity / Number of Methods', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'D - Relative Cyclomatic Complexity', 
             yaxis: 'Cyclomatic Complexity by Structure'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Classes,Abstract Classes,Concrete Classes', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'E - Types of Classes', 
             yaxis: 'Count'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Methods,Non-Static Methods,Static Methods,Public Methods,Non-Public Methods', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'F - Types of Methods', 
             yaxis: 'Count'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Constants,Global Constants,Class Constants', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'G - Types of Constants', 
             yaxis: 'Count'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Test Classes,Test Methods', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'I - Testing', 
             yaxis: 'Count'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Logical Lines of Code (LLOC),Classes Length (LLOC),Functions Length (LLOC),LLOC outside functions or classes', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'AB - Code Structure by Logical Lines of Code', 
             yaxis: 'Logical Lines of Code'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Functions,Named Functions,Anonymous Functions', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'H - Types of Functions', 
             yaxis: 'Count'
             
        plot csvFileName: 'plot-396c4a6b-b573-41e5-85d8-73613b2ffffb.csv', 
             csvSeries: [[displayTableFlag: false, 
                          exclusionValues: 'Interfaces,Traits,Classes,Methods,Functions,Constants', 
                          file: 'build/logs/phploc.csv', 
                          inclusionFlag: 'INCLUDE_BY_STRING', 
                          url: '']], 
             group: 'phploc', 
             numBuilds: '100', 
             style: 'line', 
             title: 'BB - Structure Objects', 
             yaxis: 'Count'
    }
}

        stage('SonarQube Analysis'){
            environment {
                scannerHome = tool 'SonarQubeScanner'
            }
            steps {
                echo "SonarQube Scanner Path: $scannerHome" //Debugging
                withSonarQubeEnv('sonarqube') {
                    sh '''
                        $scannerHome/bin/sonar-scanner \
                        -Dsonar.projectKey=php-todo \
                        -Dsonar.sources=. \
                        -Dsonar.php.tests.reportPath=tests/junit.xml \
                        -Dsonar.php.coverage.reportPaths=coverage.xml
                        '''
                }
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                    }
            }
        }

        stage('Package Application'){
            steps {
                sh '''
                    zip -r php-todo.zip .\
                        -x "vendor/*" \
                        -x ".git/*" \
                        -x ".env" \
                    '''
                script {
                    def server = Artifactory.server 'artifactory-server'
                    def uploadSpec = """{
                        "files": [{
                            "pattern": "php-todo.zip",
                            "target": "php-todo-local/${BUILD_NUMBER}/",
                            "props": "BUILD_NUMBER=${BUILD_NUMBER}";BRANCH=${params.branch}"
                            }]
                            }"""

                            server.upload spec: uploadSpec
                }
            }
        }
        

    }
}
