---
- hosts: todo
  become: yes
  vars:
    artifact_url: "https://artifactorykosenuel.jfrog.io/artifactory/php-todo-local/{{ artifact_version }}/php-todo.zip"
    
  tasks:
    - name: Download artifact from Artifactory
      get_url:
        url: "{{ artifact_url }}" 
        dest: "/tmp/php-todo.zip"
        url_username: jobaho5611@vidwobox.com
        url_password: "Genealogy55&"
        force: yes
        mode: '0644'
        validate_certs: no

    - name: Unzip artifact
      unarchive:
        src: "/tmp/php-todo.zip"
        dest: "/var/www/html"
        remote_src: yes
